package io.github.zznate.vectorstore.datagen.fixture;

import com.fasterxml.jackson.databind.ObjectMapper;
import io.github.zznate.vectorstore.datagen.wikipedia.WikipediaArticle;
import java.io.BufferedWriter;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.util.List;

/**
 * Writes the three-file recall fixture: {@code corpus.jsonl},
 * {@code queries.jsonl}, and {@code README.md}. The README captures every
 * piece of provenance a reader or a later regenerator needs — model, chunk
 * policy, query set, and the exact Wikipedia revision IDs used.
 */
public final class RecallFixtureWriter {

  private static final ObjectMapper JSON = new ObjectMapper();

  private final Path outputDir;

  public RecallFixtureWriter(Path outputDir) {
    this.outputDir = outputDir;
  }

  public void write(
      List<CorpusChunk> chunks,
      List<CorpusQuery> queries,
      List<WikipediaArticle> articles,
      String modelId,
      int dimension,
      int targetWords,
      int overlapWords)
      throws IOException {
    Files.createDirectories(outputDir);
    writeJsonl(outputDir.resolve("corpus.jsonl"), chunks);
    writeJsonl(outputDir.resolve("queries.jsonl"), queries);
    writeReadme(
        outputDir.resolve("README.md"),
        articles,
        modelId,
        dimension,
        chunks.size(),
        queries.size(),
        targetWords,
        overlapWords);
  }

  private static <T> void writeJsonl(Path file, List<T> items) throws IOException {
    try (BufferedWriter w = Files.newBufferedWriter(file, StandardCharsets.UTF_8)) {
      for (T item : items) {
        w.write(JSON.writeValueAsString(item));
        w.newLine();
      }
    }
  }

  private static void writeReadme(
      Path file,
      List<WikipediaArticle> articles,
      String modelId,
      int dimension,
      int chunkCount,
      int queryCount,
      int targetWords,
      int overlapWords)
      throws IOException {
    StringBuilder md = new StringBuilder();
    md.append("# Recall fixture\n\n")
        .append("Generated by `vector-store-datagen` on ")
        .append(Instant.now().toString())
        .append(".\n\n")
        .append("## Contents\n\n")
        .append("- `corpus.jsonl` — ")
        .append(chunkCount)
        .append(" chunks, one JSON object per line.\n")
        .append("- `queries.jsonl` — ")
        .append(queryCount)
        .append(" natural-language queries, each labelled with the expected article slug.\n")
        .append("- This file: provenance and regeneration instructions.\n\n")
        .append("## Embedding model\n\n")
        .append("- Model: `")
        .append(modelId)
        .append("`\n")
        .append("- Dimension: ")
        .append(dimension)
        .append("\n")
        .append("- Loaded through DJL's HuggingFace PyTorch zoo.\n\n")
        .append("## Chunking\n\n")
        .append("Whitespace-word chunker, ~")
        .append(targetWords)
        .append(" words per chunk, ")
        .append(overlapWords)
        .append("-word overlap. A word is a rough proxy for a token for the purpose of bounding\n")
        .append("embedder input size; actual WordPiece counts are ~1.3× word counts.\n\n")
        .append("## Source articles\n\n")
        .append("| Slug | Title | Wikipedia revision (oldid) |\n")
        .append("|---|---|---|\n");
    for (WikipediaArticle article : articles) {
      md.append("| `")
          .append(article.slug())
          .append("` | ")
          .append(article.title())
          .append(" | [")
          .append(article.oldid())
          .append("](https://en.wikipedia.org/?oldid=")
          .append(article.oldid())
          .append(") |\n");
    }
    md.append("\n")
        .append("## Regeneration\n\n")
        .append("```\n")
        .append("./mvnw -pl vector-store-datagen exec:java@generate-recall-fixture\n")
        .append("./mvnw -pl vector-store-datagen exec:java@validate-fixture\n")
        .append("```\n\n")
        .append("The first run downloads ~400 MB of PyTorch native libraries + the model\n")
        .append("weights into `~/.djl.ai/`. Subsequent runs are fast.\n");
    Files.writeString(file, md.toString(), StandardCharsets.UTF_8);
  }
}
